### ISSUE TITLE
Installation of this Burp Suite changed password of my Kali machine and also 3 other persons in my circle reported the same

### ISSUE THREAD

**Issue by shakilak2005** [MrPr0fessor/Burp-Suite-pro-2023#1]
When I installed the Burp Suite of MrPr0fessor, it changed root password of my Kali machine. Now its not recoverable. Also, three other friends reported the same issue by installing MrPr0fessor's Burp Suite. Why is this so? Is this something intentional?

**Comment by MrPr0fessor** [comment]
Kindly share the Screenshot, We will check the code and then update you.
